#import keysyms
#import modifier
from . import keysyms
from . import modifier

from PySide2.QtCore import *

__keysym_qt2gtk = {
    Qt.Key_Escape : keysyms.Escape,
    Qt.Key_Tab : keysyms.Tab,
    Qt.Key_Backtab : None,
    Qt.Key_Backspace : keysyms.BackSpace,
    Qt.Key_Return : keysyms.Return,
    Qt.Key_Enter : None,
    Qt.Key_Insert : keysyms.Insert,
    Qt.Key_Delete : keysyms.Delete,
    Qt.Key_Pause : keysyms.Pause,
    Qt.Key_Print : keysyms.Print,
    Qt.Key_SysReq : keysyms.Sys_Req,
    Qt.Key_Clear : keysyms.Clear,
    Qt.Key_Home : keysyms.Home,
    Qt.Key_End : keysyms.End,
    Qt.Key_Left : keysyms.Left,
    Qt.Key_Up : keysyms.Up,
    Qt.Key_Right : keysyms.Right,
    Qt.Key_Down : keysyms.Down,
    Qt.Key_PageUp : keysyms.Page_Up,
    Qt.Key_PageDown : keysyms.Page_Down,
    Qt.Key_Shift : keysyms.Shift_L,
    Qt.Key_Control : keysyms.Control_L,
    Qt.Key_Meta : keysyms.Meta_L,
    Qt.Key_Alt : keysyms.Alt_L,
    Qt.Key_CapsLock : keysyms.Caps_Lock,
    Qt.Key_NumLock : keysyms.Num_Lock,
    Qt.Key_ScrollLock : keysyms.Scroll_Lock,
    Qt.Key_F1  : keysyms.F1,
    Qt.Key_F2  : keysyms.F2,
    Qt.Key_F3  : keysyms.F3,
    Qt.Key_F4  : keysyms.F4,
    Qt.Key_F5  : keysyms.F5,
    Qt.Key_F6  : keysyms.F6,
    Qt.Key_F7  : keysyms.F7,
    Qt.Key_F8  : keysyms.F8,
    Qt.Key_F9  : keysyms.F9,
    Qt.Key_F10 : keysyms.F10,
    Qt.Key_F11 : keysyms.F11,
    Qt.Key_F12 : keysyms.F12,
    Qt.Key_F13 : keysyms.F13,
    Qt.Key_F14 : keysyms.F14,
    Qt.Key_F15 : keysyms.F15,
    Qt.Key_F16 : keysyms.F16,
    Qt.Key_F17 : keysyms.F17,
    Qt.Key_F18 : keysyms.F18,
    Qt.Key_F19 : keysyms.F19,
    Qt.Key_F20 : keysyms.F20,
    Qt.Key_F21 : keysyms.F21,
    Qt.Key_F22 : keysyms.F22,
    Qt.Key_F23 : keysyms.F23,
    Qt.Key_F24 : keysyms.F24,
    Qt.Key_F25 : keysyms.F25,
    Qt.Key_F26 : keysyms.F26,
    Qt.Key_F27 : keysyms.F27,
    Qt.Key_F28 : keysyms.F28,
    Qt.Key_F29 : keysyms.F29,
    Qt.Key_F30 : keysyms.F30,
    Qt.Key_F31 : keysyms.F31,
    Qt.Key_F32 : keysyms.F32,
    Qt.Key_F33 : keysyms.F33,
    Qt.Key_F34 : keysyms.F34,
    Qt.Key_F35 : keysyms.F35,
    Qt.Key_Super_L : None,
    Qt.Key_Super_R : None,
    Qt.Key_Menu : keysyms.Menu,
    Qt.Key_Hyper_L : None,
    Qt.Key_Hyper_R : None,
    Qt.Key_Help : keysyms.Help,
    Qt.Key_Direction_L : None,
    Qt.Key_Direction_R : None,
    Qt.Key_AltGr : None,
    Qt.Key_Multi_key : None,
    Qt.Key_Codeinput : None,
    Qt.Key_SingleCandidate : None,
    Qt.Key_MultipleCandidate : None,
    Qt.Key_PreviousCandidate : None,
    Qt.Key_Mode_switch : None,
    Qt.Key_Kanji : None,
    Qt.Key_Muhenkan : None,
    Qt.Key_Henkan : None,
    Qt.Key_Romaji : None,
    Qt.Key_Hiragana : None,
    Qt.Key_Katakana : None,
    Qt.Key_Hiragana_Katakana : None,
    Qt.Key_Zenkaku : None,
    Qt.Key_Hankaku : None,
    Qt.Key_Zenkaku_Hankaku : None,
    Qt.Key_Touroku : None,
    Qt.Key_Massyo : None,
    Qt.Key_Kana_Lock : None,
    Qt.Key_Kana_Shift : None,
    Qt.Key_Eisu_Shift : None,
    Qt.Key_Eisu_toggle : None,
    Qt.Key_Hangul : keysyms.Hangul,
    Qt.Key_Hangul_Start : keysyms.Hangul_Start,
    Qt.Key_Hangul_End : keysyms.Hangul_End,
    Qt.Key_Hangul_Hanja : keysyms.Hangul_Hanja,
    Qt.Key_Hangul_Jamo : keysyms.Hangul_Jamo,
    Qt.Key_Hangul_Romaja : keysyms.Hangul_Romaja,
    Qt.Key_Hangul_Jeonja : keysyms.Hangul_Jeonja,
    Qt.Key_Hangul_Banja : keysyms.Hangul_Banja,
    Qt.Key_Hangul_PreHanja : keysyms.Hangul_PreHanja,
    Qt.Key_Hangul_PostHanja : keysyms.Hangul_PostHanja,
    Qt.Key_Hangul_Special : keysyms.Hangul_Special,
    Qt.Key_Dead_Grave : None,
    Qt.Key_Dead_Acute : None,
    Qt.Key_Dead_Circumflex : None,
    Qt.Key_Dead_Tilde : None,
    Qt.Key_Dead_Macron : None,
    Qt.Key_Dead_Breve : None,
    Qt.Key_Dead_Abovedot : None,
    Qt.Key_Dead_Diaeresis : None,
    Qt.Key_Dead_Abovering : None,
    Qt.Key_Dead_Doubleacute : None,
    Qt.Key_Dead_Caron : None,
    Qt.Key_Dead_Cedilla : None,
    Qt.Key_Dead_Ogonek : None,
    Qt.Key_Dead_Iota : None,
    Qt.Key_Dead_Voiced_Sound : None,
    Qt.Key_Dead_Semivoiced_Sound : None,
    Qt.Key_Dead_Belowdot : None,
    Qt.Key_Dead_Hook : None,
    Qt.Key_Dead_Horn : None,
    Qt.Key_Back : None,
    Qt.Key_Forward : None,
    Qt.Key_Stop : None,
    Qt.Key_Refresh : None,
    Qt.Key_VolumeDown : None,
    Qt.Key_VolumeMute : None,
    Qt.Key_VolumeUp : None,
    Qt.Key_BassBoost : None,
    Qt.Key_BassUp : None,
    Qt.Key_BassDown : None,
    Qt.Key_TrebleUp : None,
    Qt.Key_TrebleDown : None,
    Qt.Key_MediaPlay : None,
    Qt.Key_MediaStop : None,
    Qt.Key_MediaPrevious : None,
    Qt.Key_MediaNext : None,
    Qt.Key_MediaRecord : None,
    Qt.Key_HomePage : None,
    Qt.Key_Favorites : None,
    Qt.Key_Search : None,
    Qt.Key_Standby : None,
    Qt.Key_OpenUrl : None,
    Qt.Key_LaunchMail : None,
    Qt.Key_LaunchMedia : None,
    Qt.Key_Launch0 : None,
    Qt.Key_Launch1 : None,
    Qt.Key_Launch2 : None,
    Qt.Key_Launch3 : None,
    Qt.Key_Launch4 : None,
    Qt.Key_Launch5 : None,
    Qt.Key_Launch6 : None,
    Qt.Key_Launch7 : None,
    Qt.Key_Launch8 : None,
    Qt.Key_Launch9 : None,
    Qt.Key_LaunchA : None,
    Qt.Key_LaunchB : None,
    Qt.Key_LaunchC : None,
    Qt.Key_LaunchD : None,
    Qt.Key_LaunchE : None,
    Qt.Key_LaunchF : None,
    Qt.Key_MediaLast : None,
    Qt.Key_Select : None,
    Qt.Key_Yes : None,
    Qt.Key_No : None,
    Qt.Key_Context1 : None,
    Qt.Key_Context2 : None,
    Qt.Key_Context3 : None,
    Qt.Key_Context4 : None,
    Qt.Key_Call : None,
    Qt.Key_Hangup : None,
    Qt.Key_Flip : None,
    Qt.Key_unknown : None,
    Qt.Key_Execute : None,
    Qt.Key_Printer : None,
    Qt.Key_Play : None,
    Qt.Key_Sleep : None,
    Qt.Key_Zoom : None,
    Qt.Key_Cancel : None,
    Qt.Key_MonBrightnessUp : None,
    Qt.Key_MonBrightnessDown : None,
    Qt.Key_KeyboardLightOnOff : None,
    Qt.Key_KeyboardBrightnessUp : None,
    Qt.Key_KeyboardBrightnessDown : None,
    Qt.Key_PowerOff : None,
    Qt.Key_WakeUp : None,
    Qt.Key_Eject : None,
    Qt.Key_ScreenSaver : None,
    Qt.Key_WWW : None,
    Qt.Key_Memo : None,
    Qt.Key_LightBulb : None,
    Qt.Key_Shop : None,
    Qt.Key_History : None,
    Qt.Key_AddFavorite : None,
    Qt.Key_HotLinks : None,
    Qt.Key_BrightnessAdjust : None,
    Qt.Key_Finance : None,
    Qt.Key_Community : None,
    Qt.Key_AudioRewind : None,
    Qt.Key_BackForward : None,
    Qt.Key_ApplicationLeft : None,
    Qt.Key_ApplicationRight : None,
    Qt.Key_Book : None,
    Qt.Key_CD : None,
    Qt.Key_Calculator : None,
    Qt.Key_ToDoList : None,
    Qt.Key_ClearGrab : None,
    Qt.Key_Close : None,
    Qt.Key_Copy : None,
    Qt.Key_Cut : None,
    Qt.Key_Display : None,
    Qt.Key_DOS : None,
    Qt.Key_Documents : None,
    Qt.Key_Excel : None,
    Qt.Key_Explorer : None,
    Qt.Key_Game : None,
    Qt.Key_Go : None,
    Qt.Key_iTouch : None,
    Qt.Key_LogOff : None,
    Qt.Key_Market : None,
    Qt.Key_Meeting : None,
    Qt.Key_MenuPB : None,
    Qt.Key_MySites : None,
    Qt.Key_News : None,
    Qt.Key_OfficeHome : None,
    Qt.Key_Option : None,
    Qt.Key_Paste : None,
    Qt.Key_Phone : None,
    Qt.Key_Calendar : None,
    Qt.Key_Reply : None,
    Qt.Key_Reload : None,
    Qt.Key_RotateWindows : None,
    Qt.Key_RotationPB : None,
    Qt.Key_Save : None,
    Qt.Key_Send : None,
    Qt.Key_Spell : None,
    Qt.Key_SplitScreen : None,
    Qt.Key_Support : None,
    Qt.Key_TaskPane : None,
    Qt.Key_Terminal : None,
    Qt.Key_Tools : None,
    Qt.Key_Travel : None,
    Qt.Key_Video : None,
    Qt.Key_Word : None,
    Qt.Key_Xfer : None,
    Qt.Key_ZoomIn : None,
    Qt.Key_ZoomOut : None,
    Qt.Key_Away : None,
    Qt.Key_Messenger : None,
    Qt.Key_WebCam : None,
    Qt.Key_MailForward : None,
    Qt.Key_Pictures : None,
    Qt.Key_Music : None,
    Qt.Key_Battery : None,
    Qt.Key_Bluetooth : None,
    Qt.Key_WLAN : None,
    Qt.Key_UWB : None,
    Qt.Key_AudioForward : None,
    Qt.Key_AudioRepeat : None,
    Qt.Key_AudioRandomPlay : None,
    Qt.Key_Subtitle : None,
    Qt.Key_AudioCycleTrack : None,
    Qt.Key_Time : None,
    Qt.Key_Hibernate : None,
    Qt.Key_View : None,
    Qt.Key_TopMenu : None,
    Qt.Key_PowerDown : None,
    Qt.Key_Suspend : None,
    Qt.Key_ContrastAdjust : None,
    Qt.Key_MediaPause : None,
    Qt.Key_MediaTogglePlayPause : None,
    Qt.Key_LaunchG : None,
    Qt.Key_LaunchH : None,
    Qt.Key_ToggleCallHangup : None,
    Qt.Key_VoiceDial : None,
    Qt.Key_LastNumberRedial : None,
    Qt.Key_Camera : None,
    Qt.Key_CameraFocus : None,
    Qt.Key_TouchpadToggle : None,
    Qt.Key_TouchpadOn : None,
    Qt.Key_TouchpadOff : None,
    Qt.Key_MicMute : None,
    Qt.Key_Red : None,
    Qt.Key_Green : None,
    Qt.Key_Yellow : None,
    Qt.Key_Blue : None,
    Qt.Key_ChannelUp : None,
    Qt.Key_ChannelDown : None,
    Qt.Key_Guide : None,
    Qt.Key_Info : None,
    Qt.Key_Settings : None,
    Qt.Key_Exit : None,
    Qt.Key_MicVolumeUp : None,
    Qt.Key_MicVolumeDown : None,
    Qt.Key_New : None,
    Qt.Key_Open : None,
    Qt.Key_Find : None,
    Qt.Key_Undo : None,
    Qt.Key_Redo : None,
}

def ModConv(mod):
    state = 0
    if Qt.ShiftModifier & mod:
        state |= modifier.SHIFT_MASK
    # no capslock in Qt.modifiers, we have to check keyboad status
    # nativeModifiers
    # if ...:
    #    state |= modifier.LOCK_MASK
    if Qt.ControlModifier & mod:
        state |= modifier.CONTROL_MASK
    if Qt.AltModifier & mod:
        state |= modifier.ALT_MASK
    if Qt.KeypadModifier & mod:
        state |= modifier.MOD2_MASK
    if Qt.AltModifier & mod:
        state |= modifier.ALT_MASK
    # super state |= modifier.SUPER_MASK
    if Qt.MetaModifier & mod:
        state |= modifier.META_MASK
    return state

def KeysymConv(ksym, mod):
    if Qt.Key_Space <= ksym and ksym <= Qt.Key_ydiaeresis:
        if Qt.Key_A <= ksym and ksym <= Qt.Key_Z and not mod & modifier.SHIFT_MASK:
            ksym = ksym + 32
        return ksym
    return __keysym_qt2gtk[ksym]

 
def test():
    assert(ModConv(Qt.ShiftModifier) == modifier.SHIFT_MASK)
    assert(ModConv(Qt.ControlModifier) == modifier.CONTROL_MASK)
    assert(ModConv(Qt.AltModifier) == modifier.ALT_MASK)
    assert(ModConv(Qt.MetaModifier) == modifier.META_MASK)

    assert(KeysymConv(Qt.Key_Space, 0) == keysyms.space)
    assert(KeysymConv(Qt.Key_0, 0) == keysyms._0)
    assert(KeysymConv(Qt.Key_A, 0) == keysyms.a)
    assert(KeysymConv(Qt.Key_A, modifier.SHIFT_MASK) == keysyms.A)


if __name__ == "__main__":
        test()
